#!/usr/bin/python3

import shlex
import subprocess
import sys


def run_cmd(command: str | list, hide_stdout: bool = False):
    if isinstance(command, str):
        command = shlex.split(command)
    out = subprocess.DEVNULL if hide_stdout else None
    r = subprocess.run(command, stdout=out)
    return r.returncode


def usage():
    print("gcm - git commit shortcut")
    print(f"usage: {sys.argv[0]} [message]")


def main():
    if len(sys.argv) < 2:
        usage()
        exit(1)
    if sys.argv[1] in ["-h", "--help"]:
        usage()
        exit(0)
    if len(sys.argv) == 2:
        msg = sys.argv[1]
    else:
        msg = " ".join(sys.argv[1:])
    if len(msg) < 1:
        print("Empty message")
        exit(1)
    exit(run_cmd(f"git commit -m '{msg}'"))


if __name__ == '__main__':
    main()
