#!/usr/bin/env python3

import shlex
import subprocess
import sys


def run_cmd(command: str | list, hide_stdout: bool = False):
    if isinstance(command, str):
        command = shlex.split(command)
    out = subprocess.DEVNULL if hide_stdout else None
    r = subprocess.run(command, stdout=out)
    return r.returncode


def usage():
    print("ytmp3 - download a youtube video as mp3")
    print(f"usage: {sys.argv[0]} [path]")


def main():
    if len(sys.argv) < 2 or len(sys.argv) > 2:
        usage()
        exit(1)
    if sys.argv[1] in ["-h", "--help"]:
        usage()
        exit(0)
    if len(sys.argv) == 3:
        outf = sys.argv[2]
    else:
        outf = '%(title)s.%(ext)s'
    exit(run_cmd(f"yt-dlp --extract-audio --audio-format mp3 -o {outf} {sys.argv[1]}"))


if __name__ == '__main__':
    main()
